### ISSUE TITLE
Can not find docker image

### ISSUE THREAD

**Issue by jamievaravara** [ddorgan/blockbench-docker#1]
Trying to run docker-compose up, but I get this output:

pull access denied for bbtest, repository does not exist or may require 'docker login'

What's going on? I did also run 'docker login' and successfully log in.

**Comment by ddorgan** [comment]
Can you please run ```build_docker.sh``` first. 

I have this as a step so I can keep most of the rest of the repo as close as possible to the ooibc88/blockbench.

**Comment by jamievaravara** [comment]
Cool! Thank you. 

You should add that step to your documentation btw, as step 1.

**Comment by ddorgan** [comment]
Done, see: https://github.com/ddorgan/blockbench-docker/pull/3
